"""program vector added

Revision ID: 0a179ce08a14
Revises: 5dd6abb37ac6
Create Date: 2026-02-24 22:45:08.820577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '0a179ce08a14'
down_revision: Union[str, Sequence[str], None] = '5dd6abb37ac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.add_column('program', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('program', 'embedding')
    op.execute('DROP EXTENSION IF EXISTS vector')
    # ### end Alembic commands ###
