"""programchangelog added

Revision ID: 5dd6abb37ac6
Revises: bd6ec13f229d
Create Date: 2026-02-24 20:38:19.582618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5dd6abb37ac6'
down_revision: Union[str, Sequence[str], None] = 'bd6ec13f229d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE program SET updated_at = NOW() WHERE updated_at IS NULL")
    op.alter_column('program', 'updated_at', nullable=False)
    op.create_index(op.f('ix_program_updated_at'), 'program', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_program_updated_at'), table_name='program')
    op.drop_column('program', 'updated_at')
    # ### end Alembic commands ###
