"""init schema

Revision ID: b1981f9a7ac0
Revises: 374584e4fc44
Create Date: 2026-02-24 20:07:45.596130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b1981f9a7ac0'
down_revision: Union[str, Sequence[str], None] = '374584e4fc44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program', sa.Column('temp_test_field', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('program', 'temp_test_field')
    # ### end Alembic commands ###
