"""programchangelog added

Revision ID: bd6ec13f229d
Revises: b1981f9a7ac0
Create Date: 2026-02-24 20:32:53.253586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bd6ec13f229d'
down_revision: Union[str, Sequence[str], None] = 'b1981f9a7ac0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('program', 'temp_test_field')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program', sa.Column('temp_test_field', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
